"use client";

import React from "react";
import { motion } from "framer-motion";
import { FileText, Banknote, CheckCircle2, Search } from "lucide-react";

export default function ReportsPanel() {
  const cards = [
    {
      icon: FileText,
      color: "indigo",
      title: "Technical Report View",
      desc: "AI-generated technical analysis and site verification reports are compiled here. Extracted directly from field engineers' OCR data.",
    },
    {
      icon: Banknote,
      color: "emerald",
      title: "Income Report Analysis",
      desc: "Historical income data projection and predictive behavior analysis generated by Gemini 1.5 logic.",
    },
    {
      icon: CheckCircle2,
      color: "violet",
      title: "Survey Report Auditing",
      desc: "Client satisfaction and post-disbursement survey data integrated with sentiment analysis metrics.",
    },
    {
      icon: Search,
      color: "orange",
      title: "Observation Dashboard",
      desc: "Centralized hub for manual observations, fraud detection flags, and credit deviation alerts marked by the system.",
    },
  ];

  const colorMap: Record<string, string> = {
    indigo: "bg-indigo-50 text-indigo-600 border border-indigo-100/50",
    emerald: "bg-emerald-50 text-emerald-600 border border-emerald-100/50",
    violet: "bg-violet-50 text-violet-600 border border-violet-100/50",
    orange: "bg-orange-50 text-orange-600 border border-orange-100/50",
  };

  return (
    <motion.div
      key="reports"
      initial={{ opacity: 0, scale: 0.98 }}
      animate={{ opacity: 1, scale: 1 }}
      exit={{ opacity: 0, scale: 0.98 }}
      className="grid grid-cols-1 xl:grid-cols-2 gap-6 h-full"
    >
      {cards.map((card) => (
        <div
          key={card.title}
          className="bg-white p-8 rounded-3xl border border-slate-200 shadow-sm hover:shadow-md flex flex-col items-center justify-center text-center transition-all hover:bg-slate-50/50 group"
        >
          <div
            className={`w-16 h-16 rounded-2xl flex items-center justify-center mb-6 group-hover:scale-110 transition-transform ${colorMap[card.color]}`}
          >
            <card.icon size={32} />
          </div>
          <h2 className="text-2xl font-black mb-3 text-slate-800">{card.title}</h2>
          <p className="text-slate-500 text-sm max-w-sm leading-relaxed">
            {card.desc}
          </p>
        </div>
      ))}
    </motion.div>
  );
}
