import jsPDF from "jspdf";
import "jspdf-autotable";

// Type augmentation for jsPDF with autoTable
interface jsPDFWithAutoTable extends jsPDF {
  autoTable: (options: Record<string, unknown>) => jsPDF;
  lastAutoTable: {
    finalY: number;
  };
}

export const generateProposalPDF = (data: {
  customerName: string;
  productType: string;
  finalLimit: number;
  income: number;
  assetValue: number;
}) => {
  const doc = new jsPDF() as jsPDFWithAutoTable;

  // Header Background
  doc.setFillColor(237, 27, 36); // IPDC Red
  doc.rect(0, 0, 210, 40, 'F');

  // Title in Header
  doc.setFontSize(22);
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.text("IPDC FINANCE LIMITED", 105, 18, { align: "center" });
  
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text("Driving Boundless Ambition", 105, 26, { align: "center" });

  doc.setFontSize(16);
  doc.setTextColor(40, 44, 52);
  doc.text("CREDIT FACILITY PROPOSAL", 105, 55, { align: "center" });

  // Dashboard-like Divider
  doc.setDrawColor(200, 200, 200);
  doc.setLineWidth(0.1);
  doc.line(20, 62, 190, 62);

  // Formatting helper
  const formatBDT = (num: number) => {
    return "BDT " + num.toLocaleString('en-IN');
  };

  // Customer Details Section
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`Reference: IPDC/CRM/${Math.floor(Math.random() * 9000) + 1000}`, 20, 75);
  doc.text(`Date: ${new Date().toLocaleDateString('en-GB')}`, 20, 82);

  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.setFont("helvetica", "bold");
  doc.text("Prospective Borrower Information:", 20, 95);
  doc.setFont("helvetica", "normal");
  doc.text(`${data.customerName}`, 20, 102);

  // Proposal Table
  const tableData = [
    ["Financial Parameter", "Assessment Value"],
    ["Proposed Product", data.productType],
    ["Assessed Monthly Income", formatBDT(data.income)],
    ["Security/Asset Valuation", formatBDT(data.assetValue)],
    ["MAXIMUM ELIGIBLE LIMIT", formatBDT(data.finalLimit)],
    ["Assessment Status", "AGENTIC COMPLIANCE PASSED"]
  ];

  doc.autoTable({
    startY: 110,
    head: [tableData[0]],
    body: tableData.slice(1),
    theme: "grid",
    headStyles: { fillColor: [51, 65, 85], textColor: [255, 255, 255], fontStyle: 'bold' },
    styles: { fontSize: 10, cellPadding: 5 },
    columnStyles: {
        1: { fontStyle: 'bold', textColor: [237, 27, 36] }
    }
  });

  // Footer / Disclaimer
  const finalY = doc.lastAutoTable.finalY + 30;
  
  // Signature Placeholders
  doc.line(20, finalY + 20, 70, finalY + 20);
  doc.text("Relationship Manager", 20, finalY + 25);
  
  doc.line(140, finalY + 20, 190, finalY + 20);
  doc.text("Branch Manager", 140, finalY + 25);

  doc.setFontSize(8);
  doc.setFont("helvetica", "italic");
  doc.setTextColor(150, 150, 150);
  doc.text("This document is a preliminary credit assessment generated by IPDC Intelligence Pro.", 20, finalY + 45);
  doc.text("Final approval is subject to due diligence, CIB clearance, and credit committee decision.", 20, finalY + 50);

  // Save the PDF
  doc.save(`IPDC_Proposal_${data.customerName.replace(/\s+/g, '_')}.pdf`);
};
